import { Garment, UserProfile, Outfit } from "@/types";

export const DEFAULT_PROFILE: UserProfile = {
  name: "Alex",
  genderIdentity: "Femenino / Neutro",
  bodyType: "Reloj de arena / Proporcional",
  height: "1.68m",
  skinUndertone: "warm",
  preferredStyles: ["Smart Casual", "Minimalista", "Old Money", "Casual Chic"],
  frequentContexts: ["Oficina", "Citas y Salidas", "Reuniones de trabajo", "Fines de semana"],
  favoriteColors: ["Beige", "Camel", "Blanco", "Verde Oliva", "Terracota", "Negro"],
  avoidedColors: ["Neón fluorescente", "Morado eléctrico"],
  openToBuying: true,
  completedOnboarding: true,
};

export const INITIAL_GARMENTS: Garment[] = [
  {
    id: "g-1",
    name: "Blazer Oversize Beige Estructurado",
    imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=800&auto=format&fit=crop",
    category: "outerwear",
    subcategory: "Blazer",
    primaryColors: ["Beige", "Arena"],
    colorHexes: ["#E5DCC5", "#D8CCA8"],
    pattern: "Liso / Sólido",
    silhouette: "Holgado / Oversized",
    seasons: ["primavera", "otono", "invierno", "todas"],
    formalityLevel: 4,
    material: "Mezcla de lana y viscosa",
    aiTags: ["Elegante", "Estructurado", "Versátil", "Capas"],
    createdAt: new Date().toISOString(),
    wearCount: 12,
  },
  {
    id: "g-2",
    name: "Camisa de Lino Blanco Puro",
    imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop",
    category: "top",
    subcategory: "Camisa",
    primaryColors: ["Blanco"],
    colorHexes: ["#FFFFFF"],
    pattern: "Liso / Sólido",
    silhouette: "Corte Recto",
    seasons: ["primavera", "verano", "todas"],
    formalityLevel: 3,
    material: "100% Lino",
    aiTags: ["Fresco", "Básico Esencial", "Minimalista"],
    createdAt: new Date().toISOString(),
    wearCount: 18,
  },
  {
    id: "g-3",
    name: "Pantalón Sastre Pinzas Tono Crema",
    imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800&auto=format&fit=crop",
    category: "bottom",
    subcategory: "Pantalón de Vestir",
    primaryColors: ["Crema", "Marfil"],
    colorHexes: ["#F5F2EB", "#EAE3D2"],
    pattern: "Liso / Sólido",
    silhouette: "Tiro Alto / Pierna Ancha",
    seasons: ["primavera", "verano", "otono", "todas"],
    formalityLevel: 4,
    material: "Algodón y lino",
    aiTags: ["Alarga piernas", "Elegante", "Old Money"],
    createdAt: new Date().toISOString(),
    wearCount: 9,
  },
  {
    id: "g-4",
    name: "Sneakers Blancos Minimalistas en Piel",
    imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop",
    category: "footwear",
    subcategory: "Sneakers",
    primaryColors: ["Blanco"],
    colorHexes: ["#FFFFFF"],
    pattern: "Liso / Sólido",
    silhouette: "Corte Bajo",
    seasons: ["todas"],
    formalityLevel: 2,
    material: "Piel vacuna",
    aiTags: ["Comodidad", "Casual Chic", "Esencial"],
    createdAt: new Date().toISOString(),
    wearCount: 25,
  },
  {
    id: "g-5",
    name: "Camiseta Básica de Algodón Negro",
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop",
    category: "top",
    subcategory: "Camiseta",
    primaryColors: ["Negro"],
    colorHexes: ["#18181B"],
    pattern: "Liso / Sólido",
    silhouette: "Ajustado / Slim",
    seasons: ["todas"],
    formalityLevel: 2,
    material: "100% Algodón Pima",
    aiTags: ["Básico cápsula", "Acento de contraste"],
    createdAt: new Date().toISOString(),
    wearCount: 15,
  },
  {
    id: "g-6",
    name: "Jeans Rectos Azul Índigo Clásico",
    imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop",
    category: "bottom",
    subcategory: "Jeans",
    primaryColors: ["Azul", "Azul Marino"],
    colorHexes: ["#1E3A8A", "#2563EB"],
    pattern: "Liso / Sólido",
    silhouette: "Corte Recto / Tiro Medio",
    seasons: ["todas"],
    formalityLevel: 2,
    material: "Denim rígido",
    aiTags: ["Atemporal", "Versátil", "Diario"],
    createdAt: new Date().toISOString(),
    wearCount: 22,
  },
  {
    id: "g-7",
    name: "Mocasines de Piel Marrón Tostado",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=800&auto=format&fit=crop",
    category: "footwear",
    subcategory: "Mocasines",
    primaryColors: ["Marrón", "Camel"],
    colorHexes: ["#78350F", "#C19A6B"],
    pattern: "Liso / Sólido",
    silhouette: "Clásico",
    seasons: ["primavera", "otono", "invierno", "todas"],
    formalityLevel: 4,
    material: "Piel curtida",
    aiTags: ["Elevado", "Smart Casual", "Sofisticado"],
    createdAt: new Date().toISOString(),
    wearCount: 7,
  },
  {
    id: "g-8",
    name: "Suéter de Punto Fino Camel en Cuello V",
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800&auto=format&fit=crop",
    category: "top",
    subcategory: "Suéter",
    primaryColors: ["Camel", "Terracota"],
    colorHexes: ["#C19A6B", "#C86D51"],
    pattern: "Liso / Sólido",
    silhouette: "Corte Regular",
    seasons: ["otono", "invierno", "primavera"],
    formalityLevel: 3,
    material: "Lana merino",
    aiTags: ["Cálido", "Acogedor", "Capas de entretiempo"],
    createdAt: new Date().toISOString(),
    wearCount: 11,
  },
  {
    id: "g-9",
    name: "Trench Coat Clásico Doble Botonadura",
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=800&auto=format&fit=crop",
    category: "outerwear",
    subcategory: "Trench Coat",
    primaryColors: ["Beige", "Camel"],
    colorHexes: ["#DDD4C0", "#C19A6B"],
    pattern: "Liso / Sólido",
    silhouette: "Largo / Cinturón Ajustable",
    seasons: ["primavera", "otono", "invierno"],
    formalityLevel: 4,
    material: "Gabardina repelente al agua",
    aiTags: ["Icónico", "Protección lluvia", "Elegancia urbana"],
    createdAt: new Date().toISOString(),
    wearCount: 8,
  },
  {
    id: "g-10",
    name: "Bolso Tote de Cuero Estructurado",
    imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop",
    category: "accessory",
    subcategory: "Bolso",
    primaryColors: ["Camel", "Marrón"],
    colorHexes: ["#78350F", "#C19A6B"],
    pattern: "Liso / Sólido",
    silhouette: "Estructurado",
    seasons: ["todas"],
    formalityLevel: 4,
    material: "Piel granulada",
    aiTags: ["Funcional", "Trabajo", "Pieza de acento"],
    createdAt: new Date().toISOString(),
    wearCount: 30,
  }
];

export const INITIAL_OUTFITS: Outfit[] = [
  {
    id: "outfit-1",
    title: "Old Money Elegance Urbana",
    occasion: "Oficina / Reunión Importante",
    weather: "Templado (Primavera / Otoño)",
    vibe: "Sofisticado & Pulcro",
    garmentIds: ["g-1", "g-2", "g-3", "g-7", "g-10"],
    items: [INITIAL_GARMENTS[0], INITIAL_GARMENTS[1], INITIAL_GARMENTS[2], INITIAL_GARMENTS[6], INITIAL_GARMENTS[9]],
    stylistRationale: "Paleta tonal monocromática en tonos arena y marfil que estiliza verticalmente. El contraste de texturas (lino + lana + piel tostada) aporta riqueza visual sin sobrecargar.",
    stylingTips: [
      "Mete la camisa de lino por dentro del pantalón sastre de tiro alto para marcar la cintura.",
      "Remanga ligeramente las mangas del blazer para mostrar las muñecas y dar un aire relajado pero intencional.",
      "La regla del sándwich se cumple a la perfección combinando el mocasín marrón con el bolso tote estructurado."
    ],
    colorHarmonyType: "Monocromático Tonal (Tierra y Crema)",
    missingPieceSuggestion: {
      name: "Cinturón de piel fina marrón con hebilla dorada",
      category: "accessory",
      reason: "Dará el toque final para unir el pantalón crema con los mocasines y acentuar el talle."
    },
    rating: 5,
    isFavorite: true,
    createdAt: new Date().toISOString(),
  }
];
